spring.application.name=product-service

#database configuration(These properties are used to connect to the database.)
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Admin@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#These properties are used by JPA/Hibernate after the connection is established.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
